# Generated by Django 4.1.5 on 2023-03-11 22:20

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("amount", models.IntegerField()),
                (
                    "currency",
                    models.CharField(
                        max_length=44, validators=[core.utils.is_valid_pubkey]
                    ),
                ),
                (
                    "transfer_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_out",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transfer_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_in",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Swap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "from_currency",
                    models.CharField(
                        max_length=44, validators=[core.utils.is_valid_pubkey]
                    ),
                ),
                ("from_amount", models.IntegerField()),
                (
                    "to_currency",
                    models.CharField(
                        max_length=44, validators=[core.utils.is_valid_pubkey]
                    ),
                ),
                ("to_amount", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
